name: Infrastructure

on:
    push:
        branches: [main]
        paths: ["infra/infra-website/**"]
    pull_request:
        branches: [main]
        paths: ["infra/infra-website/**"]
    workflow_dispatch:

jobs:
    plan:
        name: Plan Infrastructure Changes
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: infra/infra-website

        steps:
            - uses: actions/checkout@v5

            - name: Setup OpenTofu
              uses: opentofu/setup-opentofu@v1
              with:
                  tofu_version: ~1.10

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v5
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: OpenTofu Init
              run: tofu init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}"

            - name: OpenTofu Validate
              run: tofu validate

            - name: OpenTofu Plan
              run: tofu plan

    apply:
        name: Apply Infrastructure Changes
        runs-on: ubuntu-latest
        needs: plan
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        environment: tf-apply
        defaults:
            run:
                working-directory: infra/infra-website

        steps:
            - uses: actions/checkout@v5

            - name: Setup OpenTofu
              uses: opentofu/setup-opentofu@v1
              with:
                  tofu_version: ~1.10

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v5
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: OpenTofu Init
              run: tofu init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}"

            - name: OpenTofu Apply
              run: tofu apply -auto-approve
