name: Infrastructure

on:
    push:
        branches: [main]
        paths: ["tf/**"]
    pull_request:
        branches: [main]
        paths: ["tf/**"]
    workflow_dispatch:

jobs:
    plan:
        name: Plan Infrastructure Changes
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: tf

        steps:
            - uses: actions/checkout@v5

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: ~1.0

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v5
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Terraform Init
              run: terraform init

            - name: Terraform Validate
              run: terraform validate

            - name: Terraform Plan
              run: terraform plan

    apply:
        name: Apply Infrastructure Changes
        runs-on: ubuntu-latest
        needs: plan
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        environment: tf-apply
        defaults:
            run:
                working-directory: tf

        steps:
            - uses: actions/checkout@v5

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: ~1.0

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v5
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Terraform Init
              run: terraform init

            - name: Terraform Apply
              run: terraform apply -auto-approve
