name: Deploy Website

on:
    pull_request:
        types: [closed]
        branches: [main]
        paths: ["src/**"]
    workflow_run:
        workflows: ["Deploy Infrastructure"]
        types: [completed]
        branches: [main]
    workflow_dispatch:

permissions:
    contents: read

jobs:
    deploy-website:
        name: Deploy to S3 and CloudFront
        runs-on: ubuntu-latest
        environment: prod
        if: |
            (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
            (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')

        steps:
            - uses: actions/checkout@v5

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v5
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Sync to S3
              run: |
                  cd src
                  aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} --delete

            - name: Invalidate CloudFront
              run: |
                  aws cloudfront create-invalidation \
                    --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
                    --paths "/*"
